### PR TITLE
Update to v0.9.14 and dependencies

### PR DESCRIPTION
**Pull request by corecontingency**

### CODE REVIEW

**Comment by Cediddi** [comment]
Hi, can I help with this one. I don't want to use the appimage version and my distro packs a 5 year outdated version.

**Comment by hfiguiere** [comment]
> Hi, can I help with this one. I don't want to use the appimage version and my distro packs a 5 year outdated version.

if you know how to fix this PR (build is failing), I'd be happy to review your new PR.

(I'm don't maintain that specific package, but I can get things merged on flathub)

**Comment by Cediddi** [comment]
honestly, never tried building a flatpak and World of C/C++ is not close to me but I'll try to do some research, maybe it's just a missing include statement or version mismatch of a dependency (I really don't know :joy:)

**Comment by hfiguiere** [comment]
See #4. it should fix it.

**Pull request closed without merging**
